### ISSUE TITLE
Add a note about the CommandLineUtils dependency

### ISSUE THREAD

**Issue by tuespetre** [mrahhal/Migrator.EF6#1]
I needed to add a `NuGet.config` file to the root folder of my project's repository with the following contents in order to resolve the dependency:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    </packageSources>
</configuration>
```

**Comment by mrahhal** [comment]
You can also configure feeds globally from vs. That's what I did a long time ago, makes things easier.

I'm not doing anything fancy with `CommandLineUtils` so maybe I should make something simple and drop the dependency altogether.

**Comment by mrahhal** [comment]
You just need the following feed:

```
https://www.myget.org/F/aspnetmaster/api/v3/index.json
```

I'll add a note. Thanks!

**Comment by tuespetre** [comment]
Thank you for your work. I had not even used EF6 migrations before, only EF6 + custom migrations using DbUp. With recent projects I began using EF7 with migrations, but after hitting some limitations with EF7, needed to use EF6. Your work has just saved me :truck: of :hourglass:.

**Comment by mrahhal** [comment]
I faced the same limitations with EF7, was really disappointed. It has potential but it still needs a lot of time. Till then we have to stick with EF6, so I decided to move some of my projects in their early state to EF6, but then comes the major surprise that migrations don't work by default.

Too bad not a lot of people know about this. Glad somebody found it useful.
