### ISSUE TITLE
A couple more commands

### ISSUE THREAD

**Issue by sagoo33** [mrahhal/Migrator.EF6#13]
Hello, thanks for your work on this.

Any chance you could add the -Script command and possibly the -TargetMigration (for downgrading)?

**Comment by mrahhal** [comment]
Hi, a new release with more commands including scripting a migration is coming out really soon (possibly today).

And I think -TargetMigration already works in `1.0.0-rc2-2`. Did you try out `dotnet ef database update [target migration]`?

**Comment by sagoo33** [comment]
Awesome!

No I haven't tried that, I will do, cheers.

**Comment by mrahhal** [comment]
@sagoo33 in `1.0.0-rc2-3`:

```
dotnet ef migrations script -o output.sql
```

You can always add the `-h` option to show more help.
