### ISSUE TITLE
Possibility to have the dbcontext in a separate project

### ISSUE THREAD

**Issue by mhobl** [mrahhal/Migrator.EF6#18]
Hi @mrahhal,

First of all thank you for this great tool. It helped me a lot.

Is there a possibility to use your Migrator tooling with the dbcontext (and therefore the Migrations folder) in another project?

Kind regards,
Markus

**Comment by mrahhal** [comment]
Hi and thanks.

Please refer to #9 (read till the end).

Now that tooling preview 2 is out I'm not sure if this is still a problem. But the workaround in #9 works in all cases. (If you try it out with preview 2 and it works please let me know)

**Comment by mrahhal** [comment]
@mhobl I'm closing this, please open another issue if you're still facing a problem.
