### ISSUE TITLE
Dependency Microsoft.Extensions.CommandLineUtils.Sources cannot be resolved !

### ISSUE THREAD

**Issue by gfrSE** [mrahhal/Migrator.EF6#2]
![2016-03-24_11_10_06](https://cloud.githubusercontent.com/assets/14822146/14014161/27292dd4-f1b1-11e5-8e23-c3684836c288.png)
![2016-03-24_11_10_17](https://cloud.githubusercontent.com/assets/14822146/14014162/272973ac-f1b1-11e5-9dd8-2c5b23452f9a.png)

Can't find this Nuget package!

**Comment by mrahhal** [comment]
Did you try adding the following feed to your nuget config?

```
https://www.myget.org/F/aspnetmaster/api/v3/index.json
```

In visual studio you can go `Tools → Options` and then `NuGet Package Manager → Package Sources` and add this feed.

**Comment by gfrSE** [comment]
Damn, i read it but did not know how to use it.
Works now, sorry!

**Comment by mrahhal** [comment]
Don't worry about it, glad to help.
