### ISSUE TITLE
Support for SQLite / SQL CE

### ISSUE THREAD

**Issue by jmbalanag** [mrahhal/Migrator.EF6#20]
Hello, im trying to use SQLITE and SQLCE, however, i cant seem to properly get the correct connection string. Also, if the Migrator.EF6 can support migrations for SQLITE/CE.

**Comment by mrahhal** [comment]
Hello, `Migrator.EF6` was built to support EF6 migrations in the new tooling system of .NET Core. EF6 uses SQL Server so I can't really support other database providers if EF6 doesn't support them as far as I know. Are you using some kind of a custom adapter for EF6 to work with SQLITE? (Or is there even one to begin with?)

**Comment by mrahhal** [comment]
I'm closing this, please reopen if you still have issues.
