### ISSUE TITLE
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by jmbalanag** [mrahhal/Migrator.EF6#21]
Hello, I'm experiencing this problem:
"An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll"
even with the cloned repository.

Heres the inner exception:
{"Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.":"Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions"}

Problem is not occurring in RC2.

**Comment by jmbalanag** [comment]
Heres the inner exception:

{"Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.":"Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions"}

**Comment by jmbalanag** [comment]
Problem is not occurring in RC2.

**Comment by mrahhal** [comment]
Hello, did you make sure dependencies are restored?
Try doing `dotnet restore` and then `dotnet ef` from the command line manually to see if that worked.

**Comment by mrahhal** [comment]
@jmbalanag I'm closing this, please reopen if you still have issues.
