### ISSUE TITLE
Value cannot be null. Parameter name: type

### ISSUE THREAD

**Issue by marchy** [mrahhal/Migrator.EF6#22]
When running any of the ef commands (migrations list, add, update, database update etc.) I get the following error right after the compilation finishes:

```
Compilation succeeded.
    4 Warning(s)
    0 Error(s)
Time elapsed 00:00:03.3737613

Value cannot be null.
Parameter name: type
```

Is there any way to get more information about what might be causing this? This happens for an initial DB context for an existing database and I can't seem to isolate the issue. I've tried removing all of the code mapping from the database context file but same issue occurs.

The tooling itself is integrated (followed instructions [here](https://github.com/mrahhal/Migrator.EF6)) and the code works at runtime (ASP.NET Core 1.0 app).

**Comment by marchy** [comment]
Oh geez! finally figured it out.

We had "emitEntryPoint" set to false instead of true in project.json  _head slap_

**Comment by mrahhal** [comment]
Glad you solved it. For more info about this, check #9.
