### ISSUE TITLE
Unhandled Exception: System.ComponentModel.Win32Exception(  32 bit windows )

### ISSUE THREAD

**Issue by redpanda321** [mrahhal/Migrator.EF6#23]
c:\TEMP\demo\Migrator.EF6\samples\BasicConsoleApp>dotnet ef migrations enable
Project BasicConsoleApp (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Unhandled Exception: System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Migrator.EF6.Tools.Program.Dispatch(String[] args)
   at Migrator.EF6.Tools.Program.Main(String[] args)

**Comment by mrahhal** [comment]
More information please. Are you correctly targeting the full .NET? How does your `project.json` look like?

**Comment by redpanda321** [comment]
Sorry for response late.   I used your  sample  (https://github.com/mrahhal/Migrator.EF6/blob/master/samples/BasicConsoleApp/project.json). 

My environment 
 vs 2015 enterprise version  update3 .
  windows 7  32bit version. 
 .Net is net451.

in windows 7 64bit version is OK.

**Comment by mrahhal** [comment]
So you're trying to run the sample itself or you're just using its `project.json`? Because you must have missed something.

Well, I didn't really try that on a 32-bit machine so I'm not sure, but I can't see how that might go wrong.

**Comment by mrahhal** [comment]
@redpanda321 I'm closing this, please reopen if you still have issues.
