### ISSUE TITLE
Can't update database after scaffolding migrations

### ISSUE THREAD

**Issue by DOTang** [mrahhal/Migrator.EF6#29]
Hi, sorry to spam you with problems. I have done everything successfully per your help, but now I am trying to run the database update command and I get the following error:

> Target migration: latest
> Unable to update database to match the current model because there are pending c
> hanges and automatic migration is disabled. Either write the pending model chang
> es to a code-based migration or enable automatic migration. Set DbMigrationsConf
> iguration.AutomaticMigrationsEnabled to true to enable automatic migration.

Why is this occuring? I generated the InitialCreate migration. It has all the create tables in it, but I can't update it. I try to generate another Migration file just to see what pending changes they are talking about, but it just generates the exact same migration file as the InitialCreate.

**Comment by DOTang** [comment]
Well it seems I have forgot to reset emitEntryPoint = true, however after doing that and running it I get a different error now:

> Automatic migration was not applied because it would result in data loss. Set Au
> tomaticMigrationDataLossAllowed to 'true' on your DbMigrationsConfiguration to a
> llow application of automatic migrations even if they might cause data loss. Alt
> ernately, use Update-Database with the '-Force' option, or scaffold an explicit
> migration.

Okay, not sure why that happen as my model didn't change, but easy enough fix, I set it to true, try and run again, same error. But then, when I check the database, it actually still generated the tables! Unfortunately I don't know at which step this actually happened, but at least according to the messages I never ran a successful database update, but it did work.

**Comment by DOTang** [comment]
Well, now it works lol. I really don't know what happened. All I did was truncate, delete the InitialCreate migration from project. Rerun the initial create, database update again, and now no errors.

**Comment by mrahhal** [comment]
Don't worry about it, my plan is to allow everybody to work with the new project system + EF6 + Migrations instead of being blocked simply because someones thought it's not worth it to create this in the tooling :)

This occurs when your models/migrations are not up to date with the database. So you can try deleting the database when this happens again and it should work.

it usually happens because you:
1. Created InitialCreate
2. Played a bit more with the models
3. Tried updating (this won't work)

You should always update after adding a migration, or recreate it if you didn't update yet.

**Comment by DOTang** [comment]
Yeah I know, I checked that, I didn't make any changes to the models at all and the second migration I tried to generate was the 100% exact same as the first one. Would running the VS command prompt in admin have an impact on this? I remember that is one thing I changed between trying to get it to work the first time vs the second.

**Comment by mrahhal** [comment]
Hmm nope, admin mode doesn't change anything. Things like that might happen when you're tinkering and trying to get it to work (a mismatch between the migration and the actual model), but once you're off hopefully this doesn't happen again.
