### ISSUE TITLE
"Sequence contains no matching element" error when -c options specifies missing/mis-typed context

### ISSUE THREAD

**Issue by marchy** [mrahhal/Migrator.EF6#38]
Can we get a better error showing when mistyping the context when specifying the -c option?
Something like "No such context: {context name}"

Currently it shows "Sequence contains no matching element" which can send you on quite a chase not knowing what the issue is.

**Comment by mrahhal** [comment]
Thanks for reporting this. Will do this in the next version.

**Comment by marchy** [comment]
@mrahhal Awesome stuff Mohammed. Thanks for taking care of so quickly  :)

**Comment by mrahhal** [comment]
Will release the patch today, no worries :)

**Comment by marchy** [comment]
No rush Mohammed. Whenever the next release goes out – it's not a critical one.

PS: Way to release the VS 2017 support so shortly after it's launch. Really appreciated this enabling us to fully move over and start enjoying the C# 7 goodness  =)
