### ISSUE TITLE
'ApplicationDbContext' does not contain a definition for 'Add' 

### ISSUE THREAD

**Issue by joshiji** [mrahhal/Migrator.EF6#4]
Hi,
I am getting below error when I am trying to use EF6 as per your code samples. 

`'ApplicationDbContext' does not contain a definition for 'Add' and no extension method 'Add' accepting a first argument of type 'ApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)`

However, since you are doing any database operations, I am not able to figure out if I am missing anything here. Do I need to add some reference here?

Best Regards,
Santosh

**Comment by mrahhal** [comment]
Hi,
Is this happening in the samples provided or in your own project? If it's in your project could you try out the sample and see if this happens there as well?

**Comment by mrahhal** [comment]
Hi,
I don't remember `DbContext` having an `Add` method. Maybe this is true for EF Core but not for EF6? I can't quite remember.

You should do `context.Blogs.Add(myBlog)` where Blogs is a property of type `DbSet<Blog>`.

Or you can write the following extension method and that would work:

``` cs
public static void Add<T>(this DbContext @this, T entity)
    where T : class
    => @this.Set<T>().Add(entity);
```

**Comment by joshiji** [comment]
Thanks. Now I see it. I have started asp.net with asp.net 5 directly so had
only experience with EF7. Thanks for clarification.

**Comment by mrahhal** [comment]
No worries, glad to help.
