### ISSUE TITLE
Version 1.1.1 will cause the CMD window crash

### ISSUE THREAD

**Issue by viewtance** [mrahhal/Migrator.EF6#40]
Latest version 1.1.1, when running "dotnet ef database update", it could cause the CMD windows crashed, that the "dotnet-ef" window will stop working.

With .net framework 4.6.1 environment. It throw below exception:

Unhandled Exception: System.InvalidOperationException: Could not invoke tool dotnet-ef.
   at Microsoft.Extensions.Internal.DotnetToolDispatcher.EnsureValidDispatchRecipient(String[]& programArgs, String toolName)
   at Migrator.EF6.Tools.Program.Main(String[] args)

**Comment by mrahhal** [comment]
Are you running migrations inside your web app? After dotnet tooling 1.0 (VS 2017), there's an issue that prevents the tool from running inside an app that references Mvc. Check the README, there's a section that starts with "IMPORTANT" for more info about this, and about how to resolve it.

If that's not your issue, I need more info about what you tried and if 1.1.1 is the only version that causes the issue as implied.

**Comment by viewtance** [comment]
I am not using it in web app, it is used in a individual project that provide EntityFramework migration for .net core on windows platform.

If I rollback to version 1.1.0 it works fine.

**Comment by mrahhal** [comment]
The only thing I'm suspicious of causing this between 1.1.0 and 1.1.1 is [this commit](https://github.com/mrahhal/Migrator.EF6/commit/f7a5eb5b85865f967cc540702d19641b0e143769). I had to do this to prevent an exception being thrown when running tests in mac (if memory serves). Not sure of the consequences but it looked harmless.

I tested with the samples in this repo and with another one of my projects running in production and everything worked fine with 1.1.1.

Is this only an issue with `database update` and not the other commands? Does this happen with newly created projects from scratch? Does this happen in both console apps and class libs?

If you could provide a repro then that would be most helpful.

**Comment by reberinformatik** [comment]
Same issue here (also with 1.1.3) after upgrading from 1.1.0. We have a solution depending on aspnetzero and are using VS 2017. 
The csproj of the EF project is as follows:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0.0.0</VersionPrefix>
    <TargetFramework>net461</TargetFramework>
    <AssemblyName>PreRec.EntityFramework</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>PreRec.EntityFramework</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace>PreRec</RootNamespace>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PreRec.Core\PreRec.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Migrator.EF6.Tools" Version="1.1.1" />
    <PackageReference Include="Abp.Zero.EntityFramework" Version="2.0.2" />
    <PackageReference Include="Abp.EntityFramework" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.1.0" /> <-- now downgraded to 1.1.0 to make it work.
  </ItemGroup>

</Project>
```

**Comment by reberinformatik** [comment]
By writing the previous comment I probably found the issue ;)
```diff
   <ItemGroup>
-    <PackageReference Include="Migrator.EF6.Tools" Version="1.1.1" />
+    <PackageReference Include="Migrator.EF6.Tools" Version="1.1.3" />
     <PackageReference Include="Abp.Zero.EntityFramework" Version="2.0.2" />
     <PackageReference Include="Abp.EntityFramework" Version="2.0.2" />
   </ItemGroup>
@@ -36,7 +36,7 @@
   </ItemGroup>
 
   <ItemGroup>
-    <DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.1.0" />
+    <DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.1.3" />
   </ItemGroup>
 
 </Project>
```
So we have to update `<DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.1.3" />`

**Comment by mrahhal** [comment]
@reberinformatik thanks for confirming. I'll now close this, @viewtance feel free to reopen if the problem persists after correcting the versions.
