### ISSUE TITLE
Crash after calling dotnet ef enable

### ISSUE THREAD

**Issue by armille3** [mrahhal/Migrator.EF6#41]
I'm using VS2017 with EF 6.1.3 and ASP.NET Core 1.1.  I'm running this on a class library project.  However, after the project builds the tool crashes with this error:

Unhandled Exception: System.InvalidOperationException: Could not invoke tool dotnet-ef.
   at Microsoft.Extensions.Internal.DotnetToolDispatcher.EnsureValidDispatchRecipient(String[]& programArgs, String toolName)
   at Migrator.EF6.Tools.Program.Main(String[] args)

**Comment by mrahhal** [comment]
You might want to make sure you did everything right. It's probable that you've missed something. Make sure there's a "PackageReference" and a "CliToolReference" and that you restored your project (dotnet restore).

You can also try running the samples in this repository. Does the same problem occur?

**Comment by armille3** [comment]
Thanks for the quick response.  Just tried the sample command line project and it enabled the migrations just fine.

My .csproj file does have those lines in it, any ideas of anything else I should check?  Also did a restore, and same error.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <AssemblyName>Drs.Framework.Repositories</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Drs.Framework.Repositories</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Drs.Framework.Core\Drs.Framework.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.0.2" />
    <PackageReference Include="AutoMapper.EF6" Version="1.0.0" />
    <PackageReference Include="EntityFramework" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="1.1.0" />
    <PackageReference Include="Migrator.EF6.Tools" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.6.13" />
  </ItemGroup>
  
  <ItemGroup>
	<DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System.Data" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
```

**Comment by mrahhal** [comment]
Maybe the problem is that the "DotNetCliToolReference" is including a different version? Make sure it's the same "1.1.1" version. After you edit the csproj, VS should restore automatically, but you can also make sure by running "dotnet restore".

**Comment by armille3** [comment]
You're right, that appeared to be it!  I just copied and pasted from your readme on the website.   You may want to change the version number so other's don't have this problem.  Thanks again.

**Comment by mrahhal** [comment]
Ah, sorry about that. Didn't notice. Will change it soon, thanks.
