### ISSUE TITLE
Ensure the tool works with the new .net 2.0 sdk

### ISSUE THREAD

**Issue by mrahhal** [mrahhal/Migrator.EF6#47]

**Comment by nphmuller** [comment]
I'm in the progress of migrating my applications to the new Core 2.0 SDK. (Targeting net462)

Can confirm that adding migrations, updating and downgrading the database works with version 1.1.4 of the tool.

**Comment by mrahhal** [comment]
@nphmuller as always, thanks! Was hoping someone would confirm.

**Comment by mrahhal** [comment]
v2.0.0 has explicit support for .net sdk 2.0, it's recommended over the previous versions.
