### ISSUE TITLE
Rename Param ConnectionString to ConnectionStringForMigration

### ISSUE THREAD

**Issue by xrkolovos** [mrahhal/Migrator.EF6#48]
Rename Param ConnectionString to ConnectionStringForMigration

**Comment by mrahhal** [comment]
Which `ConnectionString` do you mean?

**Comment by hadiidbouk** [comment]
@xrkolovos  jewib = answer !!

**Comment by xrkolovos** [comment]
@hadiidbouk what do you mean?

`public static string ConnectionString { get; set; } `

**Comment by mrahhal** [comment]
@xrkolovos this is in the sample project. You can just name it whatever you want in your own DbContext.

**Comment by mrahhal** [comment]
But as an aside, `ConnectionStringForMigration` doesn't make much sense. This property will always be used by the DbContext. Its initial hard coded value is what gets used by the migrator.
