### ISSUE TITLE
Microsoft.DotNet.Cli.Utils cannot install in asp.net core 2 project with Migrator.EF6

### ISSUE THREAD

**Issue by joeizang** [mrahhal/Migrator.EF6#50]
I am trying to add Migrator.EF6 to aspnetcore 2 solution and I get Severity	Code Package restore failed. Rolling back package changes for 'ProjectName'. I installed all the dependencies and its Microsoft.DotNet.Cli.Utils that fails. What can I do to resolve this issue?

**Comment by mrahhal** [comment]
Please try using `dotnet ef` in the sample in this repo and follow it in your own project.

It's probably something you didn't configure right or forgot to do. Please read the README and the steps contained within to get this to work.

**Comment by joeizang** [comment]
ok will try this and see. Thank you

**Comment by joeizang** [comment]
I am so sorry for raising what actually isn't an issue. I will close this issue and report back if there is any thing else. I will just create the class library.

**Comment by mrahhal** [comment]
No worries. Let me know if something isn't obvious in the README or if you face further problems.
