### ISSUE TITLE
Porting to RC2

### ISSUE THREAD

**Issue by tuespetre** [mrahhal/Migrator.EF6#6]
I would like to help port this project to RC2:
- Adopting a `netstandard` target framework moniker
- Accounting for the `dotnet` CLI's 'tools' paradigm, which replaced 'commands'
- Dropping the dependency on the 'command line sources'
- Consider seeking inclusion in https://github.com/aspnet-contrib
- Consider changing the version to `1.0.0-rc2`, along with a rename to allow a proper transition to a 'true' `1.0.0` when the time comes

**Comment by mrahhal** [comment]
Thanks. Actually I was already doing it (the migration) but then I faced a problem with installing dotnet core inside the CI environment (appveyor) and I haven't had time to look into it yet.
Basically it used to work but then RC2 was changing fast just before the release yesterday. I think we can look into how `KoreBuild` is doing it and move from there.

So to address your points:
- We'll be running as a dotnet tool under the `netstandard` tfm in the new version.
- We'll drop the dependency on the command line sources package.
- Wouldn't mind being included in aspnet-contrib.
- Was already considering aligning the version numbers to that of Asp.Net Core releases.

So next version should be `1.0.0-rc2` I guess though I'm not sure if this will cause problems with nuget.

**Comment by tuespetre** [comment]
Didn't mean to close this.

**Comment by mrahhal** [comment]
I figured out how to work with dotnet cli in CI. I'm currently porting a couple of related projects and then I'll come back to this.

**Comment by tuespetre** [comment]
DotNet CLI tools need to be `netcoreapp1.0`, it seems. Doesn't like there's a clean solution to this since EF6 needs the full framework (`mscorlib` with `ICloneable`, etc.)

**Comment by mrahhal** [comment]
Yeah, forgot about that. So actually, we'll be using the `net451` tfm because EF6 only runs on the full framework.

**Comment by mrahhal** [comment]
Sorry, having a bad day.

Yeah, forgot about that. I'll be looking into this.

**Comment by mrahhal** [comment]
There is a way to still make this work (by design). The tool is always invoked under `netcoreapp1.0` but it can somehow re-invoke itself again. Apparently ef and razor tooling do that.

But for now there is too little info on the subject so I'm still looking.

**Comment by mrahhal** [comment]
There's still a small problem with getting a tool to run on the full `net` in an experiment, I'm working to resolve this.

After I figure this out I'll create an `rc2` branch (though it won't live long).
A couple of points:
- We can still use the command line sources package, no need to drop it. (A lot of tools use it)
- I'm considering changing the package name to a more appropriate name so that I can also align the version with that of coreclr.

**Comment by mrahhal** [comment]
Check the [rc2](https://github.com/mrahhal/Migrator.EF6/tree/rc2) branch.

**Comment by tuespetre** [comment]
Brilliant, can't wait to try it out. Just went on vacation today so it will be a few days but thanks again for the tremendous help you've given the community wth this project!

**Comment by mrahhal** [comment]
Glad it helped. Happy vacation!
