### ISSUE TITLE
Version 3.0.0 doesn't seem to be published

### ISSUE THREAD

**Issue by Fancy11111** [mrahhal/Migrator.EF6#69]
Hi, I tried to install Version 3.0.0 like this today:
`dotnet tool install --global Migrator.EF6.Tools --version 3.0.0-*`
but it seems like it hasn't been published yet

Here's the error I'm getting:

```
error NU1102: Unable to find package migrator.ef6.tools with version (>= 3.0.0)
error NU1102:   - Found 23 version(s) in nuget.org [ Nearest version: 2.1.0 ]
error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error NU1102:   - Found 0 version(s) in C:\Program Files\dotnet\sdk\NuGetFallbackFolder
The tool package could not be restored.
Tool 'migrator.ef6.tools' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

Am I missing something?
Is there any other way installing this tool?
Any help or clarification is appreciated.

**Comment by mrahhal** [comment]
Well, there's no 3.0.0 yet..
There are several problems I'm not sure how to fix, at https://github.com/mrahhal/Migrator.EF6/pull/68.

**Comment by Fancy11111** [comment]
Ah sorry, I misunderstood the README then.
Should I close this Issue?

**Comment by mrahhal** [comment]
No worries. I'll close it. You can subscribe to https://github.com/mrahhal/Migrator.EF6/pull/67, so that if things go well you'll be notified.
