### ISSUE TITLE
JOIN Tables fails in NetCore 3.0 & EF6.3 with Method syntax (but works with Query...)

### ISSUE THREAD

**Issue by GuyBenhaim** [mrahhal/Migrator.EF6#70]
Hello,
With EDMX migration code I fail in joining two tables: using Method syntax the properties of the 2nd table do not appear and prevent defining the InnerKeySelctor (Only the External Declaration options appear). 
This causes an error and I cannot compile.

Example:
var list = db.PP.Where(pp => pp.F0 == 1).Join(db.OP, pp => pp.F1, **op => op.**  , (pp, op) => new {pp, op}).Select(pp => pp.F3_ID).ToList();
**Here for op the properteis do not appear.** 

Surprisingly, using Query syntax the properties appear and the join is performed ok.

Please advise.

**Comment by mrahhal** [comment]
Hello,

.Net Core 3.0 isn't supported yet, I have a couple of problems I still have to solve (but currently at a stalemate as I have no clue how to proceed on this). You can follow the progress at https://github.com/mrahhal/Migrator.EF6/issues/67.

**Comment by GuyBenhaim** [comment]
Hello,
I was actaully referring to the example code that Diego from MS has provided to enable supporting EDMX  and .NetCore 3

**Comment by mrahhal** [comment]
In that case, I honestly not sure how Migrator.EF6 fits here. This is just a tool to create migration files and has nothing to do with runtime.

**Comment by GuyBenhaim** [comment]
ok, thx
